### ISSUE TITLE
I'm logged in but the homescreen still shows "Please login to view"

### ISSUE THREAD

**Issue by SuyashLakhotia** [googleinterns/step203-2020#117]
![Screenshot 2020-07-24 at 2 06 40 PM](https://user-images.githubusercontent.com/8863065/88364912-fe280900-cdb6-11ea-899d-0464dc76a371.png)

**Comment by lisasgoh** [comment]
It's because theres no deals data yet

**Comment by limli** [comment]
A better message might be "There are no deals" rather than "Please log in to view"
